### ISSUE TITLE
Fix CONTRIBUTING.rst's docstring bug about fixing bugs

### ISSUE THREAD

**Issue by onstash** [AlexMathew/scrapple#95]
@AlexMathew The docstring says `Look through the GitHub issues for bugs. Anything tagged with "bug" is open to whoever wants to implement it` instead of `Look through the GitHub issues for bugs. Anything tagged with "bug" is open to whoever wants to fix it`.

**Comment by AlexMathew** [comment]
@thesantosh You can go ahead with a fork of the repo and make this change. Let me know once the PR is up

**Comment by onstash** [comment]
@AlexMathew Pull request https://github.com/AlexMathew/scrapple/pull/97 has been raised.
