### ISSUE TITLE
Scrapple version in __init__.py is not synced with the PyPi version

### ISSUE THREAD

**Issue by onstash** [AlexMathew/scrapple#98]
Suggestion: Let `version` be part of a config file, from which you import it for `README.[rst/md]` and `scrapple.__init__.py`.

**Comment by AlexMathew** [comment]
The ideal thing to do is to just remove it. Rather not have code in an init file. Because this is primarily a command line tool, it's more important to have the version number right in the argument parser.

**Comment by onstash** [comment]
Sounds good to me. So who will be working on this?

**Comment by AlexMathew** [comment]
The version numbers are synced up as of now, so there is nothing to do here.
