### ISSUE TITLE
scrapple.utils.exceptions.handle_exceptions(args) needs fixes

### ISSUE THREAD

**Issue by onstash** [AlexMathew/scrapple#99]
A couple of fixes are possible here - 

- Function name `handle_exceptions(..)` could be renamed to `check_arguments(..)` or something similar because usually handling exceptions involve `try-except` blocks.
- Gracefully handling `TypeError` and `ValueError` exceptions for `int(args['--levels'])` on [#31](https://github.com/AlexMathew/scrapple/blob/master/scrapple/utils/exceptions.py#L31).
- Raising an ultra generic `Exception` / `BaseException` is an [anti-pattern](https://docs.quantifiedcode.com/python-anti-patterns/correctness/no_exception_type_specified.html) and hence difficult to debug, if we encounter bugs.

If there are multiple fixes, then it can either be raised as different pull-requests and merged in or as a single pull-request and squash the commits before/while merging.

**Comment by AlexMathew** [comment]
@thesantosh You can get to working on this. Send in a PR when it's set.

**Comment by onstash** [comment]
I just saw the comment. Will raise a PR at the earliest.

**Comment by AlexMathew** [comment]
There's no rush. Do it on your own time. Just let me know if you need any help around the codebase.
